### ISSUE TITLE
 Maengelliste Fehlermeldung.

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/veriso#37]
Heute kommt beim anwählen eines Punktes aus der Maengelliste folgende Fehlermeldung.

 

Traceback (most recent call last):

                                     File "/home/agiri/.qgis2/python/plugins/veriso/modules/tools/defects_list.py", line 149, in on_defects_list_currentItemChanged

                                       self._zoom_to_feature(fid)

                                     File "/home/agiri/.qgis2/python/plugins/veriso/modules/tools/defects_list.py", line 116, in _zoom_to_feature

                                       feature = self.layer.getFeatures(request).next()

                                   RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

Mit den Daten auf dem Server im Share:
/home/agiri/Schreibtisch/Share/AVOR_PNF2.1/Schwendibach/

**Comment by marioba** [comment]
The problem cannot be reproduced even with the same data. Probably was caused by some kind of "session" problem in QGIS, solved with a restart of the program.
